spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:~/tsetdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        platform: h2
        schema: classpath:/schema-h2.sql
        sql-script-encoding: UTF-8
        initialization-mode: always
    jpa:
        database: h2
        hibernate:
            ddl-auto: update
        generate-ddl: true
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
              trace: true

server:
  port: 9001

file:
  dir: ~/Document/excel/